#!/bin/bash

echo "🚀 TENZING DEPLOY HELPER"
echo "========================="

echo ""
echo "✅ TUDO PRONTO PARA DEPLOY!"
echo ""
echo "📋 PRÓXIMOS PASSOS:"
echo ""
echo "1️⃣ BACKEND (Railway):"
echo "   URL: https://railway.app/new"
echo "   Root: / (vazio)"
echo "   Start: python main.py"
echo "   Vars: MONGO_URL, DB_NAME, PORT"
echo ""
echo "2️⃣ FRONTEND (Vercel):"
echo "   URL: https://vercel.com/new" 
echo "   Root: frontend"
echo "   Build: yarn build"
echo "   Output: build"
echo ""
echo "3️⃣ DOMÍNIO:"
echo "   Vercel → Settings → Domains"
echo "   Adicionar: tenzing.com.br"
echo ""
echo "4️⃣ DNS (GoDaddy):"
echo "   Seguir instruções da Vercel"
echo ""
echo "🎯 RESULTADO: https://tenzing.com.br"
echo ""
echo "📱 Custos: ~$5-10/mês"
echo "⏱️  Tempo: ~5-10 minutos"
echo ""
echo "🆘 Dúvidas? Me chame!"